rust/psibase/src/boot.rs
rust/psibase/src/http.rs
rust/psibase/src/lib.rs
rust/psibase/src/main.rs
rust/psibase/src/method_number.rs
rust/psibase/src/services/auth_ec_sys.rs
rust/psibase/src/services/common_sys.rs
rust/psibase/src/services/mod.rs
rust/psibase/src/services/nft_sys.rs
rust/psibase/src/services/proxy_sys.rs
rust/psibase/src/services/psispace_sys.rs
services/user/NftSys/include/services/user/NftSys.hpp

Add rust wrappers for the following services:
- auth-ec-sys
- common-sys
- nft-sys
- proxy-sys
- psispace-sys

Add psispace wrapper

---

services/system/AccountSys/ui/src/App.tsx
services/system/AccountSys/ui/src/helpers.ts
services/user/CommonSys/common/rpc.d.ts
services/user/CommonSys/common/rpc.mjs
services/user/CommonSys/ui/src/hooks/useApplets.tsx
services/user/CommonSys/ui/src/views/nav.tsx

This addresses two items in the project backlog:
1. Clicking on account circle in CommonSys nav bar should take user to the AccountSys app
2. Closes #124

CommonSys account circle indication improvements

---

rust/psibase/src/table.rs
rust/test_service_elections/src/lib.rs

Found a better design for the table wrappers and getting secondary key index.

Table wrapper with secondary keys

---

rust/psibase_macros/src/service_macro.rs
rust/test_service_elections/src/lib.rs

Add tables macros

---

services/user/CommonSys/common/rpc.d.ts
services/user/CommonSys/common/rpc.mjs
services/user/CommonSys/ui/src/hooks/useApplets.tsx
services/user/PsiSpaceSys/ui/package.json
services/user/PsiSpaceSys/ui/src/components/files-manager/files-manager.tsx
services/user/PsiSpaceSys/ui/src/components/files-manager/path-breadcrumbs.tsx
services/user/PsiSpaceSys/ui/src/main.tsx
services/user/PsiSpaceSys/ui/src/styles/globals.css
services/user/PsiSpaceSys/ui/yarn.lock

History changes synced with main frame address

---

services/system/AccountSys/ui/src/appInit.ts
services/user/CommonSys/common/rpc.d.ts
services/user/CommonSys/common/rpc.mjs
services/user/CommonSys/ui/src/hooks/useApplets.tsx

Implements message metadata and add getproof check

---

services/user/FractalSys/include/services/user/fractalTables.hpp
services/user/FractalSys/src/FractalSys.cpp
services/user/launchTestChain/test/src/launchTestChain.cpp

Closes https://github.com/gofractally/psibase/issues/328
The query
```
query {
getFractals(user: "alice")
{
edges {
node {
key {
fractal
}
}
}
}
}
```
Will return, for example
```
{
"data": {
"getFractals": {
"edges": [
{
"node": {
"key": {
"fractal": "astronauts"
}
}
}
]
}
}
}
```

Fractal sys improvements

---

services/user/FractalSys/ui/.prettierrc.json
services/user/FractalSys/ui/package.json
services/user/FractalSys/ui/src/main.tsx
services/user/FractalSys/ui/src/pages/create-fractal/create-fractal.tsx
services/user/FractalSys/ui/src/pages/home/home-sidebar.tsx
services/user/FractalSys/ui/src/pages/index.ts
services/user/components/.prettierrc.json
services/user/components/package.json
services/user/components/src/styles/inputs.css
services/user/components/src/ui/Form.tsx
services/user/yarn.lock

Initial create-fractal UI. 
- this is just the first step (fractal information) of the two step wizard
- no meeting definition/scheduling step
- Land on and implement a sane set of languages and language codes (I'll work on that on Monday)
- Replace existing file upload control with a drag-and-drop control matching designs

Create Fractal UI

---

programs/psitest/main.cpp

- The default of no logging remains unchanged
- `-v` is equivalent to `Severity >= info`
- Repeating `-v` is increases it to `Severity >= debug`
- Adds a `--log-filter` option to allow more precise control

psitest logging

---

generator/tools/templates/react/yarn.lock
services/system/AccountSys/ui/package.json
services/system/AccountSys/ui/src/components/Icon.tsx
services/system/AccountSys/ui/yarn.lock
services/user/AdminSys/ui/package.json
services/user/AdminSys/ui/src/components/icon.tsx
services/user/AdminSys/ui/yarn.lock
services/user/CommonSys/common-lib/yarn.lock
services/user/CommonSys/ui/src/components/icon.tsx
services/user/CommonSys/ui/yarn.lock
services/user/ExploreSys/ui/package.json
services/user/ExploreSys/ui/yarn.lock
services/user/InviteSys/ui/yarn.lock
services/user/PsiSpaceSys/ui/src/components/icon.tsx
services/user/PsiSpaceSys/ui/yarn.lock
services/user/TokenSys/ui/src/components/icon.tsx
services/user/TokenSys/ui/yarn.lock
services/user/yarn.lock

I also had to modify all the copies of Icon.tsx, because it was failing with a type error.

upgrade js dependencies

---

libraries/psibase/common/include/psibase/check.hpp

Add missing #include

---

libraries/psio/include/psio/view.hpp
libraries/psio/tests/test_fracpack.cpp

Tested at `clang version 16.0.4`

Fixes for clang

---

libraries/debug_eos_vm/dwarf.cpp
libraries/debug_eos_vm/locals.hpp

- https://github.com/gofractally/eos-vm/pull/9

Update eos-vm and make dwarf support handle new layout of globals

---

libraries/psibase/native/tests/WatchdogTests.cpp

This time, repeat the test multiple times and allow up to 25% to overrun the expected time.

Yet another attempt at fixing WatchdogTest

---

libraries/psibase/CMakeLists.txt
libraries/psibase/native/include/psibase/prefix.hpp
libraries/psibase/native/src/prefix.cpp
libraries/psibase/tester/include/psibase/DefaultTestChain.hpp
libraries/psibase/tester/include/psibase/package.hpp
libraries/psibase/tester/include/psibase/tester.hpp
libraries/psibase/tester/include/psibase/zip.hpp
libraries/psibase/tester/src/DefaultTestChain.cpp
libraries/psibase/tester/src/package.cpp
libraries/psibase/tester/src/tester.cpp
libraries/psibase/tester/src/wasi_polyfill/__wasi_environ_get.cpp
libraries/psibase/tester/src/wasi_polyfill/__wasi_environ_sizes_get.cpp
libraries/psibase/tester/src/wasi_polyfill/__wasi_path_filestat_get.cpp
libraries/psibase/tester/src/zip.cpp
programs/psinode/main.cpp
programs/psitest/main.cpp
services/user/launchTestChain/test/src/launchTestChain.cpp

- Adds environment variable support to psitest
- Fixes psitest's handling of absolute paths

Use packages in DefaultTestChain

---

doc/psidk/src/run-infrastructure/cli/psibase.md
rust/Cargo.lock
rust/psibase/Cargo.toml
rust/psibase/src/main.rs
rust/psibase/src/package.rs

`--package-source http://admin-sys.psibase.127.0.0.1.sslip.io:8080/packages`
Or looking towards the future: `--package-source https://packages.psibase.io/`

psibase can fetch packages from a remote repository

---

libraries/psio/src/fpconv.c

Also revert clang-format, since this is third-party code.

Update fpconv.c from upstream. Fixes #572.

---

services/user/CommonSys/ui/yarn.lock

Might want to double check it builds for you on this branch @brandonfancher

regenerate common-sys lockfile

---

libraries/psibase_http/http.cpp

Some refactoring of http.cpp

---

CMakeLists.txt
rust/CMakeLists.txt

Fixes service tests no longer running

move cargo tests into subdirectory

---

doc/psidk/src/specifications/app-architecture/supervisor.md

added clarification around primary diagram as well as a code snippet and some explanatory text.
I'm going to leave this PR open for further tweaking as we converge on a Supervisor API.

Augmenting doc for Supervisor/wasm-loader

---

libraries/psibase/sdk/pack_service.cmake

Skip creating the intermediate temporary directory with symlinks, so that there are no left over broken symlinks.

Fix cmake copy_directory failure when switching branches. 

---

services/user/CommonApi/common/packages/common-lib/yarn.lock

Update common-lib dependencies

---

doc/psidk/src/specifications/blockchain/peer-consensus/joint-consensus.md
libraries/net/include/psibase/bft.hpp
libraries/net/test/test_bft_consensus.cpp

Trigger a view change when enough joint producers advance

---

services/system/AuthK1/src/RAuthK1.cpp
services/user/Fractal/src/Fractal.cpp
services/user/Invite/src/Invite.cpp

qualify all std::move calls

---

services/user/Tokens/src/RTokens.cpp

* Adds the `userTokens` query to the tokens query service. This can be used to look up any tokens for which the current user owns the issuer NFT.
* Also, this PR updates the `.ownerDetails` field in the `tokenDetails` query to be an optional value. This field will be empty if, for example, the issuer NFT has been burned.

Add `userTokens` query

---

rust/psibase/src/services/accounts.rs
services/system/Accounts/plugin/Cargo.lock
services/system/Accounts/plugin/Cargo.toml
services/system/Accounts/plugin/src/errors.rs
services/system/Accounts/plugin/src/lib.rs
services/system/Accounts/plugin/wit/world.wit

These are the changes made in the mm/identity-plugin branch as part of the identity service/plugin

Add getAccount() to Accounts plugin

---

doc/psidk/src/specifications/app-architecture/supervisor.md

docs: update supervisor.md

---

libraries/psibase/common/include/psibase/blob.hpp

Just for fun/practice.
Also increases readability, probably improves error messages...

add some concepts to blob compare

---

libraries/net/include/psibase/blocknet.hpp
services/user/Nft/src/Nft.cpp

Silences two of the warnings I noticed in build output

Fix warnings

---

libraries/psibase/common/include/psibase/db.hpp
libraries/psibase/common/include/psibase/nativeTables.hpp
libraries/psibase/native/src/NativeFunctions.cpp
rust/psibase/src/boot.rs
rust/psibase/src/db.rs
rust/psibase/src/native_tables.rs
rust/psibase/src/services/producers.rs
services/psibase_tests/event-service.cpp
services/psibase_tests/event-service.hpp
services/psibase_tests/test_event.cpp

WARNING: Incompatible changes to layout. Chain reset required.

Cleanup to native databases

---

.github/workflows/ubuntu-builder.yml

- https://github.com/gofractally/image-builders/pull/39
- https://github.com/gofractally/image-builders/pull/42

Update docker images

---

CMakeLists.txt
doc/psidk/src/development/services/rust-service/package.md
libraries/psibase/sdk/pack_service.cmake
services/user/Branding/Cargo.lock
services/user/Branding/Cargo.toml
services/user/Branding/service/Cargo.toml

Fixes #895 
Now includes UI.
Now is part of Dev and Prod packages

Updating Branding packaging

---

programs/psinode/main.cpp

A mysterious failed transaction showed up in the stats.

Fix transaction stats for boot

---

libraries/psibase/common/include/psibase/serveGraphQL.hpp
libraries/psibase/tester/include/psibase/tester.hpp
libraries/psio/include/psio/graphql.hpp
services/user/Tokens/src/RTokens.cpp
services/user/Tokens/test/src/Tokens-test.cpp

- Add TransformedConnection which applies a function to the elements of an index.
- Use new features in RTokens
- Add tests for Tokens queries
Fixes #214

Generalize argument merging for GraphQL

---

libraries/psibase/common/include/psibase/Actor.hpp
libraries/psibase/common/include/psibase/Service.hpp
libraries/psibase/common/include/psibase/dispatch.hpp
services/psibase_tests/subjective-service.cpp
services/system/AuthDelegate/src/AuthDelegate.cpp
services/user/Nft/src/Nft.cpp
services/user/Symbol/src/Symbol.cpp
services/user/Tokens/src/Tokens.cpp

Recusion safety for C++ services

---

services/user/Supervisor/ui/src/callStack.ts

Callstack-related console output is getting ridiculous

clean up callstack-related browser console output

---

libraries/psio/include/psio/graphql.hpp

Fix cpp graphql schema generation including variants

---

libraries/psibase/native/src/useTriedent.cpp

It's outdated and crashes. I don't think that having a parallel implementation is particularly useful anyway.

Remove db sanityCheck.

---

rust/Cargo.lock
rust/psibase/src/graph_ql.rs
rust/psibase/src/time.rs
rust/test_contract_2/Cargo.toml
rust/test_contract_2/src/lib.rs

Simplify making graphql-pagination-style queries for event data

---

rust/psibase/src/crypto.rs

Removes an `unsafe` block from rust, and resolves a warning

Fix psibase warning

---

CMakeLists.txt
rust/psibase/src/services/auth_delegate.rs
services/system/AuthDelegate/CMakeLists.txt
services/system/AuthDelegate/include/services/system/AuthDelegate.hpp
services/system/AuthDelegate/include/services/system/RAuthDelegate.hpp
services/system/AuthDelegate/plugin/Cargo.toml
services/system/AuthDelegate/plugin/src/errors.rs
services/system/AuthDelegate/plugin/src/lib.rs
services/system/AuthDelegate/plugin/wit/impl.wit
services/system/AuthDelegate/plugin/wit/world.wit
services/system/AuthDelegate/src/AuthDelegate.cpp
services/system/AuthDelegate/src/RAuthDelegate.cpp
services/system/AuthSig/include/services/system/RAuthSig.hpp
services/user/Packages/src/Packages.cpp
services/user/Packages/src/RPackages.cpp
services/user/Registry/service/src/lib.rs

Propagate release/v0 patch

---

rust/psibase/src/rpc.rs

- Make TransactionBuilder's handling of the limit consistent with boot (upper bound rather than lower bound on tx size).
- Reset the variable that stores the total size after each transaction so that we don't think that every later actions needs its own transaction.

Fix excessive transaction splitting

---

package-templates/basic-01/{{project-name | upper_camel_case}}/query-service/src/lib.rs
package-templates/basic-01/{{project-name | upper_camel_case}}/ui/src/App.tsx
package-templates/basic-01/{{project-name | upper_camel_case}}/ui/src/hooks/use-create-connection-token.ts
package-templates/basic-01/{{project-name | upper_camel_case}}/ui/src/hooks/use-current-accounts.ts
package-templates/basic-01/{{project-name | upper_camel_case}}/ui/src/hooks/use-logged-in-user.ts
package-templates/basic-01/{{project-name | upper_camel_case}}/ui/src/hooks/use-logout.ts
package-templates/basic-01/{{project-name | upper_camel_case}}/ui/src/hooks/use-select-account.ts
package-templates/basic-01/{{project-name | upper_camel_case}}/ui/src/main.tsx

* use new EventQuery class for paginated event query
* use supervisor singleton
* remove explicit login call

Package template updates

---

rust/cargo-psibase/src/main.rs

Remove use of --suppress-ok from cargo-psibase

---

doc/psidk/src/development/services/cpp-service/basic/CMakeLists.txt
doc/psidk/src/development/services/cpp-service/basic/README.md
doc/psidk/src/development/services/cpp-service/calling/README.md
doc/psidk/src/development/services/cpp-service/minimal-ui/CMakeLists.txt
doc/psidk/src/development/services/cpp-service/minimal-ui/README.md
doc/psidk/src/development/services/cpp-service/reference/web-services.md
doc/psidk/src/development/services/cpp-service/setup.md
doc/psidk/src/development/services/rust-service/basic/README.md
doc/psidk/src/development/services/rust-service/calling.md
doc/psidk/src/development/services/rust-service/graphql.md
doc/psidk/src/development/services/rust-service/minimal-ui.md
doc/psidk/src/development/services/rust-service/reference/web-services.md
doc/psidk/src/development/services/rust-service/setup.md
doc/psidk/src/development/services/rust-service/tables.md
doc/psidk/src/development/services/rust-service/testing.md
doc/psidk/src/development/services/webassembly.md

It was quite badly out-dated in places.

Update documentation examples

---

services/user/Evaluations/query-service/src/lib.rs
services/user/Evaluations/service/src/db.rs
services/user/Evaluations/service/src/hooks.rs

Here's a starter hook module for your eval service, and also I added an example secondary index with a query for it

hooks module; secondary index query

---

package-templates/basic-01/{{project-name | upper_camel_case}}/plugin/Cargo.toml.liquid

Prevents tests written in plugin files from compiling

fix erroneous dev-dependency in plugin

---

programs/psinode/tests/test_psibase.py
rust/psibase/src/main.rs

- Show package versions
- Only show one version of each package
- Include installed packages even if they are not present in the repo

Improve psibase search subcommand

---

doc/psidk/src/run-infrastructure/cli/psibase.md
programs/psinode/tests/test_psibase.py
rust/psibase/src/main.rs
rust/psibase/src/package.rs

This allows the CLI to push arbitrary actions, which makes scripting somewhat easier.

Add psibase push subcommand

---

.gitmodules
external/CMakeLists.txt
libraries/psibase/CMakeLists.txt
libraries/psibase/sdk/psibase-config.cmake
libraries/psibase/sdk/psibase-config.cmake.build
libraries/psibase/tester/src/tester.cpp
wasm/CMakeLists.txt

Remove secp256k1 submodule

---

.vscode/scripts/build.sh

I was having trouble getting the build to succeed. @James-Mart suggested I modify this value. It worked.

Update build script JOBS value

---

services/user/Evaluations/Cargo.lock

missed updating this in my last PR

Updating Evaluations Cargo.lock

---

services/user/Fractals/service/src/scoring.rs
services/user/Fractals/service/src/tables.rs

Cleaning up misc warnings that got delivered with the fractal service.

fix warnings in fractals service

---

services/user/Tokens/include/services/user/tokenTypes.hpp

Precision was missing the pack/json serde logic in C++

add pack/unpack to cpp precision type

---

rust/psibase/src/main.rs

Similar to #1237. We don't need to wait for one package to finish uploading before sending the next one.

Publish packages faster

---

CMakeLists.txt
libraries/psibase/tester/src/tester.cpp
packages/local/CMakeLists.txt
packages/local/XTransact/CMakeLists.txt
packages/local/XTransact/include/services/local/XTransact.hpp
packages/local/XTransact/src/XTransact.cpp
packages/system/Transact/src/RTransact.cpp

Add x-transact

---

rust/psibase/src/package.rs

found a flag that was being mapped incorrectly

Updating bad flag mapping

---

CMakeLists.txt
packages/local/XAdmin/ui/src/hooks/useProducers.ts

Fixes https://github.com/gofractally/psibase/issues/1447

XAdmin: Avoid querying producers unless we've successfully booted

---

libraries/psibase/native/include/psibase/BlockContext.hpp
libraries/psibase/native/src/BlockContext.cpp
libraries/psibase/tester/include/psibase/tester.hpp
libraries/psibase/tester/include/psibase/testerApi.hpp
libraries/psibase/tester/src/tester.cpp
packages/psibase_tests/include/services/test/SubjectiveCounterService.hpp
packages/psibase_tests/src/SubjectiveCounterService.cpp
packages/psibase_tests/test/test_subjective.cpp
programs/psitest/main.cpp
rust/psibase/src/block.rs
rust/psibase/src/tester.rs
rust/psibase/src/tester_raw.rs

Also adds replay support to tester

Add tests for runModeRpc and runModeCallback

---

programs/psinode/main.cpp

The native option doesn't actually do anything, since the addition of the CpuLimit service.

Remove leeway option
