rust/psibase/src/native.rs, rust/psibase/src/table.rs, rust/psibase/src/to_key.rs, rust/test_service_elections/src/lib.rs
Initialize secondary keys.
Currently working functionalities:
- inserting new keys
- updating keys when record is updated and change is relevant
- removing keys when record is removed
Next steps:
- Explore better type handling for secondary keys, heterogeneous lists, macros etc.
- Implement the macros itself for the tables
=> Init secondary keys

rust/psibase/src/table.rs, rust/psibase/src/time.rs, rust/psibase_macros/src/service_macro.rs, rust/test_service_elections/src/lib.rs
- Adds `open_custom` method on the TableHandler which will allow the share of a specific table among different contracts
- Fix the iterator `next()` when the `back_key` is empty
- Overall improvements in the elections contracts example
- Full getter elections method with a working cursor (and tests for it)
=> Overall elections example improvements

rust/psibase/src/native.rs, rust/psibase/src/table.rs, rust/test_service_elections/src/lib.rs
Addresses few past review suggestions from PR https://github.com/gofractally/psibase/pull/209
- Split TbIndex from Iter
- Add idiomatic Range
- Improves secondary keys checks when replacing or writing new ones passing the abort control to the user
=> Table improvements

rust/Cargo.toml, rust/psibase/src/serve_http.rs, rust/psibase/src/table.rs, rust/psibase_macros/src/service_macro.rs, rust/test_service_elections/src/lib.rs, rust/test_service_psispace/Cargo.toml, rust/test_service_psispace/README.md, rust/test_service_psispace/src/lib.rs
- Replicates psispace-sys in rust
- Implements table.erase
- Adds number of secondary keys in the `Table` trait (to optimize erase operation)
- General improvements on the election service (now it supports current time and serves the simple ui)
- Improves table interface adding the methods: `new(), with_service() and with_prefix()`
=> Replicates psispace in rust

CMakeLists.txt, rust/psibase/src/boot.rs
Adds a new directory inside boot-image that can be entirely deleted & recreated by cmake. This avoids [this glob expansion issue](https://github.com/gofractally/psibase/issues/239#issuecomment-1343528947) and still allows `boot-image/` to be bind-mounted outside of a docker container.
After this update, devs should run `rm -rf /root/psibase/rust/psibase/boot-image/*` inside their environments to manually clear out the boot-image.
=> add new subdirectory to boot image to avoid glob expansion issue

rust/psibase/src/serve_http.rs, rust/psibase_macros/src/graphql_macro.rs, rust/psibase_macros/src/lib.rs, rust/psibase_macros/src/service_macro.rs, rust/test_service_psispace/Cargo.toml, rust/test_service_psispace/src/lib.rs
Queries can be implemented by using the following macros:
```
#[queries]
impl Queries {
/// List all the existing files
table_query!(content, ContentTable, get_index_pk: ContentKeyNamed);
/// List files content by account subindex
table_query_subindex!(
content_by_account,
ContentTable,
get_index_pk,
account: AccountNumber
);
}
```
- `table_query!` is used to wrap an index function and its named keys type with the `first, last, before, after, gt, ge, lt, le` query functions
- `table_query_subindex!` is used to wrap a subindex for a given index function and the defined subindex partial fields.  
- the last parameter of this query can set the subindex RemainingKey type if it's a single ident parameter such as `Vec<u8>`, `String`, `MyStruct`
=> Add Contract Queries Macros

services/user/CommonSys/ui/src/views/applet.tsx
Addresses #283 
- The query string params are only being passed if it's the current page main applet.
- As an example, the psispace applet makes use of the account applet. Imagine it's accessed through this URL: `http://psibase.127.0.0.1.sslip.io:8081/applet/psispace-sys?folder_path=/foo/bar`. The query param `?folder=/foo/bar` is not relevant for the account applet. Thus this param will be passed to the psispace applet only, because we know the main applet is derived from `/applet/psispace-sys`.
- If the query param is relevant to other sister applets it should be responsibility of the invoker to communicate to the invoked applet, through the traditional messaging infrastructure (via queries or actions).
=> Add query params to main applet

libraries/net/include/psibase/bft.hpp, libraries/net/test/CMakeLists.txt, libraries/net/test/afl-clang-lto++.in, libraries/net/test/bft_fuzz.cpp, libraries/net/test/bft_fuzz.txt, libraries/net/test/test_bft_consensus.cpp, libraries/psibase/native/include/psibase/ForkDb.hpp
Depends on [AFL++](https://aflplus.plus/). The fuzz harness can be compiled standalone, but it will be much less useful.  To build with AFL++ ensure that `afl-clang-lto++` is in your path and pass `-DPSIBASE_FUZZER=AFL` to CMake.
The parameters that I've been using are:
```
afl-fuzz -G 2048 -t 2000 native/libraries/net/test/bft_fuzz
```
For best results compilation should use Release+Asserts (-O3 but *not* -DNDEBUG).
=> Fuzzing with AFL

CMakeLists.txt, rust/psibase/src/boot.rs, services/system/AccountSys/ui/src/appInit.ts, services/system/AuthEcSys/ui/README.md, services/user/CommonSys/common/rpc.d.ts, services/user/CommonSys/ui/src/hooks/useApplets.tsx, services/user/InviteSys/ui/src/index.d.ts, services/user/InviteSys/ui/src/service.ts, services/user/InviteSys/ui/src/store/queries/fetchUser.ts
Refactored as in #289 
The only missing part is refactoring out the KeyStore to the new KeyVault applet (still TBD).
=> GetAuthedTransaction refactored to CommonSys

services/user/CommonSys/common/rpc.mjs
Fix #293 
I double checked that `window.location.replace()` is the desired effect to not give the traditional infinite back button ugliness effect.
=> Fix redirectIfAccessedDirectly history

services/user/CommonSys/common/rpc.mjs, services/user/CommonSys/ui/src/helpers.ts, services/user/CommonSys/ui/src/views/applet.tsx, services/user/InviteSys/ui/src/layouts/default.tsx, services/user/InviteSys/ui/src/pages/options/options.tsx
When we were accessing the applet subpath address directly (by copying and pasting a link / sharing a link) we were seeing the following issue:
1. This PR fixes the above issue.
2. Also fixes the #107 
3. Fixes an issue on invite-sys because the applet was being initialized only when the root path (`/`) was being called, making a directly call to `invite-sys/signup?token=....` to fail. I moved the `useInitialize`  hook call to the Layout parent component.
=> Fix direct access to applet subpath

doc/psidk/src/psibase/README.md, doc/psidk/src/psibase/logging.md, libraries/psibase/native/include/psibase/ConfigFile.hpp, libraries/psibase/native/src/ConfigFile.cpp, programs/psinode/config.in, programs/psinode/main.cpp
This addresses #370 and supersedes #372.
=> Allow environmental variables in config

CMakeLists.txt, doc/psidk/src/SUMMARY.md, doc/psidk/src/psibase/README.md, doc/psidk/src/psibase/psibase.md, doc/psidk/src/psibase/psinode.md, rust/Cargo.lock, rust/Cargo.toml, rust/md2man/Cargo.toml, rust/md2man/src/main.rs
- Add docs for `psibase` commands other than boot
- Allow generation of man pages for psibase and psinode
=> Move psibase and psinode into separate documentation pages

.github/workflows/ubuntu-2004.yml, .github/workflows/ubuntu-2204.yml
Doc build needs to run gen-cpp-doc, which means it needs to run under CMake instead of a direct call to mdbook.
=> Fix cpp docs in github actions

doc/psidk/src/psibase/logging.md, libraries/net/include/psibase/blocknet.hpp, libraries/net/test/fuzz.hpp, libraries/psibase/native/include/psibase/BlockContext.hpp, libraries/psibase/native/include/psibase/ForkDb.hpp, libraries/psibase/native/include/psibase/log.hpp, libraries/psibase/native/src/BlockContext.cpp, libraries/psibase/native/src/log.cpp, programs/psinode/config.in
Block logging is modified to use a scoped logger attribute instead of a scoped thread attribute, so that the block header and block id are not inherited by the transaction logger.  When I originally wrote the block logging, I thought that including the BlockId and header in the transaction log would be useful, but after actually trying it, it just makes the logs more verbose.
=> Add transaction logging

.vscode/launch.json.sample, .vscode/tasks.json.sample, services/user/CMakeLists.txt
Sample file that can be used to give vscode debug launch configurations using psitest
=> VSCode service debugging - add launch.json.sample

libraries/net/test/test_util.cpp, libraries/psibase/native/src/BlockContext.cpp, libraries/psibase/tester/src/DefaultTestChain.cpp, programs/psinode/main.cpp, rust/Cargo.lock, rust/psibase/Cargo.toml, rust/psibase/src/boot.rs, rust/psibase/src/main.rs, rust/psibase/src/services/transaction_sys.rs, services/system/TransactionSys/include/services/system/TransactionSys.hpp, services/system/TransactionSys/src/TransactionSys.cpp
- push_boot gets two transactions, the genesis transaction, and a transaction that initializes TransactionSys with a list of the remaining boot transactions ids.  The rest of the boot transactions are pushed with push_transaction.
- TransactionSys enforces that the extra boot transactions are pushed in order.
- psinode defers handling non-push_boot transactions until after the genesis block.
=> Split boot across multiple blocks. Fixes #239.

libraries/net/include/psibase/peer_manager.hpp
I'm not sure what I was thinking in checking `info.size()`. `peers.size()` is definitely the right thing to check, because we're indexing into peers.
=> Fix crash on disconnect.

libraries/psibase/native/src/ExecutionContext.cpp
The key that was inserted in the cache was uninitialized which mostly prevented modules from being reused, but sometimes also used the wrong module.
=> Fix wasm cache

.github/workflows/ubuntu-2004.yml, .github/workflows/ubuntu-2204.yml, CMakeLists.txt
The new image uses wasi-sdk-~17~19.0. 14.0 appears to not work quite right with simd enabled. 17.0 doesn't support ubuntu 20.
=> Update 20.04 image

.vscode/launch.json.sample
In .gdbinit I had `add-auto-load-safe-path /root/psibase/build/psidk/lib/debug/psitest-gdb.py`
But here I changed it to `add-auto-load-safe-path /root/psibase/build/psidk/lib/debug/`, because it's supposed to add a safe dir.
=> add gdbinit commands relative to workspace

libraries/triedent/include/triedent/location_lock.hpp, libraries/triedent/src/ring_allocator.cpp
Both of these cause spurious notifications.
=> Fix uninitialzed variables

libraries/psibase_http/http.cpp
When we close a connection due to a timeout, we should not depend on the client closing the other end of the connection.
=> Fix close on timeout

generator/tools/templates/react/yarn.lock, services/system/AccountSys/ui/yarn.lock, services/user/AdminSys/ui/yarn.lock, services/user/CommonSys/common-lib/yarn.lock, services/user/CommonSys/ui/yarn.lock, services/user/ExploreSys/ui/yarn.lock, services/user/InviteSys/ui/yarn.lock, services/user/PsiSpaceSys/ui/yarn.lock, services/user/TokenSys/ui/yarn.lock, services/user/yarn.lock
This is the result of running `yarn upgrade`.  Quite a few packages have new major versions, but upgrading to those will take significantly more work as just using `--latest` gives errors because of incompatible changes.
=> Update js dependencies

.github/scripts/build.sh, .github/workflows/ubuntu-builder.yml
Extracts into a bash script the functionality from the github workflow that mounts the source into a docker container for building. Github workflow calls the new script.
Script can also be reused outside CI/CD context to more easily reproduce the ci/cd build locally.
=> add build bash script, use from workflow

rust/psibase/src/boot.rs
This closes #504 by restoring the third-party dependencies that were removed. We can clean up third-party dependencies as a separate effort later.
Tested simpleUI working with this change by visiting the proxy-sys service UI.
=> Fix simpleUI

libraries/psibase/CMakeLists.txt
For a little while, building a C++ psibase service would fail if relying on a third-party install of wasi-sdk and psidk.
The reason is that we were installing the `psibase-config.cmake` toolchain config file into the wrong location.
This PR fixes that (corrects the install location so builds are now successful).
=> Fix third-party C++ service development

programs/psinode/main.cpp
It's not really an error, psinode can still run, albeit slower, without locking db memory. Log severity therefore has been reduced from `error` to `warning`.
=> Reduce log severity when psinode can't lock db memory

libraries/net/test/test_bft_consensus.cpp
The `io_context` can stop if all the nodes are disconnected, which causes subsequent connect to not work. This is only a problem in the test. In psinode itself, there's always something to keep the io_context alive.
=> Fix bug in test case

programs/psinode/main.cpp
- --version should not be usable in the config file
- --help should be listed in its own output
- --version=false doesn't make a lot of sense
=> Minor tweaks to options

doc/psidk/src/run-infrastructure/cli/psibase.md, rust/Cargo.lock, rust/psibase/Cargo.toml, rust/psibase/src/boot.rs, rust/psibase/src/crypto.rs
This allows all key arguments to take a PKCS #11 URI. Such arguments will be interpreted as using `verify-sys`.
The module can be specified in the URI (e.g. `?module-name=libsofthsm2`). If a module name is not specified, the default is `p11-kit-proxy.so`, which loads a system-specific set of modules.
`psibase` assumes by default that public key objects are public on the token and private key objects are private. It will prompt for a pin only for private keys. If a pin is provided in the URI (`pin-value` or `pin-source`), then it will login with that pin to access both public and private keys.
=> PKCS #11 support for psibase

doc/https.md, doc/psidk/src/run-infrastructure/cli/psibase.md, doc/psidk/src/specifications/data-formats/package.md, generator/tools/templates/react/deploy.sh, rust/psibase/src/main.rs, services/system/AuthEcSys/ui/README.md, services/system/AuthSys/ui/README.md, services/user/AdminSys/ui/README.md, services/user/CommonSys/ui/README.md, services/user/FractalSys/ui/package.json, services/user/InviteSys/ui/package.json, services/user/PsiSpaceSys/include/services/user/PsiSpaceSys.hpp, services/user/PsiSpaceSys/ui/README.md
- Add `-r` which subsumes the functionality of `upload-tree`
- Make content-type an optional argument and default to deducing it from the file name
- Reorder the source and dest to be more consistent with unix conventions
- Make dest optional. With `-r`, the dest defaults to `/` which is almost always going to be the right thing. Without `-r`, the destination is derived from the source file name. i.e. `path/to/index.html` will be uploaded to `/index.html`
- If the dest does not have a leading `/`, add one automatically.
=> rework psibase upload

doc/psidk/src/run-infrastructure/cli/psibase.md, libraries/psibase/native/src/TransactionContext.cpp, libraries/psibase_http/http.cpp, libraries/psibase_http/include/psibase/http.hpp, libraries/psio/include/psio/from_json.hpp, libraries/psio/include/psio/to_json.hpp, programs/psinode/main.cpp, programs/psinode/tests/psinode.py, rust/Cargo.lock, rust/psibase/Cargo.toml, rust/psibase/src/main.rs, rust/psibase/src/rpc.rs, rust/psibase/src/trace.rs, services/user/AdminSys/ui/src/boot-wizard/boot-page.tsx
- Change psio json serialization of variant to {type:value} to match serde. It's the same number of characters and the serde version seems more sane.
- Allow rust deserialization of TransactionTrace to handle number-as-string.
- Ensure that the ActionTrace::error field is set
- Add --trace=error|stack|full|json to determine the verbosity
=> Show service stack trace on transaction failure

services/user/CommonSys/common/messaging/index.ts, services/user/CommonSys/common/messaging/supervisor.ts, services/user/CommonSys/common/messaging/supervisor/PreLoadServicesRequest.ts, services/user/DemoApp1/ui/package.json, services/user/DemoApp1/ui/src/App.tsx, services/user/DemoApp1/ui/tsconfig.json, services/user/DemoApp1/ui/vite.config.ts, services/user/DemoApp1/ui/yarn.lock, services/user/PsiSpaceSys/ui/yarn.lock, services/user/SupervisorSys/ui/src/main.ts
Introduces the ability to spin up for iframes of services we know we will use ahead of time, later on this could potentially be automatic if we track dependencies further. 
This also adds a new method for the supervisor package `await supervisor.onLoaded();` which ensures we do not attempt to send messages to the iframe before it's initialized. This wasn't needed before because of the time it takes a user to engage communication. 
I was getting type issues with `@messaging` which went away with the removal of `include: src/ui` in the `tsconfig.json` everything else seems to be running okay.
=> add pre-loading

services/system/AuthAnySys/include/services/system/AuthAnySys.hpp, services/system/AuthAnySys/src/AuthAnySys.cpp, services/system/AuthDelegateSys/include/services/system/AuthDelegateSys.hpp, services/system/AuthDelegateSys/src/AuthDelegateSys.cpp, services/system/AuthEcSys/include/services/system/AuthEcSys.hpp, services/system/AuthEcSys/src/AuthEcSys.cpp, services/system/AuthSys/include/services/system/AuthSys.hpp, services/system/AuthSys/src/AuthSys.cpp, services/system/ProducerSys/include/services/system/ProducerSys.hpp, services/system/ProducerSys/src/ProducerSys.cpp, services/system/TransactionSys/include/services/system/TransactionSys.hpp, services/system/TransactionSys/src/TransactionSys.cpp, services/user/InviteSys/include/services/user/AuthInviteSys.hpp, services/user/InviteSys/src/AuthInviteSys.cpp
This should increase the effective maximum action size, though it doesn't fully resolve it.
=> Change checkAuthSys signature to avoid passing the potentially large data, which is never actually used.

doc/psidk/src/run-infrastructure/configuration/logging.md, libraries/psibase/native/src/BlockContext.cpp, libraries/psibase/native/src/log.cpp, libraries/psibase_http/http.cpp, programs/psinode/config.in
The default format shows it indented 4 spaces. The output is controlled by the service author and is not sanitized. Beware if sending it to an automated consumer.
=> Add logging of transaction and query console output

CMakeLists.txt
After merging `main` into `dev/plugins`, the build broke. Packages now require version numbers. This was missing for SupervisorSys. Added now.
=> Fix dev/plugins build

wasm/CMakeLists.txt
This helps anyone who is using clang-format, they can point it at `build/wasm/compile-commands.json` to get better autocomplete.
This is already configured in the [psibase-contributor](https://github.com/gofractally/psibase-contributor) tool.
=> generate wasm compile-commands.json

services/user/DemoApp2/plugin/Cargo.lock, services/user/DemoApp2/plugin/Cargo.toml, services/user/DemoApp2/plugin/src/lib.rs
This is included in John's PR, but this bumps the bindings version 1 more minor version and gets these building in the feature branch.
=> Upgrade DemoApp2 for cargo component 0.9.0

rust/psibase/src/graph_ql.rs, rust/psibase/src/native.rs, rust/psibase_macros/src/service_macro.rs, rust/test_contract_2/src/lib.rs
This basically mirrors the existing C++ API for emission.
GraphQL support is significantly simplified.
```
#[event(history)]
fn created(prevEvent: u64, tokenId: TID, creator: AccountNumber, precision: Precision, max_supply: Quantity) {}
...
Wrapper::emit().ui().created(prev, tid, creator, precision, max_supply);
...
let e: event_structs::HistoryEvents = get_event(id)?;
let e: event_structs::history::created = get_event(id)?;
```
=> Add event emission in rust

.github/scripts/build.sh
Sparky pointed out that the build script wasn't updated since
https://github.com/gofractally/psibase/pull/569
=> Remove outdated flags from build script

CMakeLists.txt
- The dist directory is marked as an input for other rules, so ninja needs to know that it is created.
- Make the component copy conditional, to avoid triggering spurious rebuilds
- `BUILD_BYPRODUCTS` refers to the build step, not the install step.
=> CMake fixes

CMakeLists.txt
```
CMake Warning (dev) at CTestTestfile.cmake:1:
Syntax Warning in cmake code at column 17
```
=> Fix ctest warning

libraries/psibase/native/tests/WatchdogTests.cpp
The multi-threaded test already allows overrun some of the time. I've been seeing occasional failures in the single-threaded test instead now.
=> Relax the single-threaded timer accuracy test

libraries/psibase/common/include/psibase/AccountNumber.hpp, libraries/psibase/common/include/psibase/schema.hpp, libraries/psio/include/psio/schema.hpp, libraries/psio/src/schema.cpp, services/user/Events/src/REvents.cpp, services/user/Events/src/types.cpp, services/user/Events/test/EventsTest.cpp, services/user/Events/test/TestService.cpp, services/user/Events/test/TestService.hpp
- Converted to a Custom type in schema
- A collation sequence that matches the ordering of accounts is applied to columns with the AccountNumber type.
- Indexes ignore constraints that require collation sequences that do not match the collation sequence of the indexed column.
=> Handle AccountNumbers as query keys

CMakeLists.txt, doc/psidk/src/specifications/app-architecture/events.md, services/user/Tokens/include/services/user/Tokens.hpp, services/user/Tokens/include/services/user/tokenTables.hpp, services/user/Tokens/src/RTokens.cpp, services/user/Tokens/src/Tokens.cpp
Tested the event system using the following query, which works:
```
// To: https://events.psibase.127.0.0.1.sslip.io:8080/sql
SELECT * FROM "history.tokens.transferred" where receiver="alice" ORDER BY ROWID
```
```
[
{
"tokenId": "1",
"time": {
"seconds": 1715629976
},
"sender": "symbol",
"receiver": "alice",
"amount": {
"value": "100000000000"
},
"memo": "memo"
}
]
```
=> support new tokens event indexing using events service

.vscode/tasks.json.sample, libraries/psibase/common/include/psibase/db.hpp, libraries/psibase/common/include/psibase/serveGraphQL.hpp, programs/psinode/tests/test_psibase.py, services/user/Tokens/include/services/user/tokenTables.hpp, services/user/Tokens/src/RTokens.cpp, services/user/XAdmin/ui/yarn.lock
This adds a new capability to graphql queries in C++: A vector of objects dynamically constructed at query time can be more easily queried using graphql.
The tokens query service uses this to allow for pagination on a dynamically constructed vector of objects, rather than returning the entire vector.
-------
New queries:
1. `userBalances(AccountNumber user, ...pagination)`
2. `userCredits(AccountNumber user, ...pagination)`
3. `userDebits(AccountNumber user, ...pagination)`
4. `tokenDetails(TID tokenId)`
The first three queries manually construct an index that combines the normal balance table row with details about the token (symbolID and precision) in order to return all relevant details within a single query.
The fourth new query `tokenDetails` returns details about a token given its …
=> Improve token service graphql queries

libraries/psio/include/psio/from_json.hpp, services/user/Fractal/test/src/manual-fractal-test.cpp, services/user/Symbol/src/Symbol.cpp, services/user/Symbol/test/src/Symbol-test.cpp, services/user/Tokens/include/services/user/tokenTypes.hpp, services/user/Tokens/src/RTokens.cpp, services/user/Tokens/src/TokenUsers.json, services/user/Tokens/src/Tokens.cpp, services/user/Tokens/test/src/Tokens-test.cpp
* Sets max precision to 8 instead of 16
* Updates the precision class so min/max are enforced when unpacking from frackpack or json
* Updates the precision of the system token to 4
* Updates a bunch of tests to look up the previously hardcoded sys token precision
=> Reduce system token precision

libraries/psibase/common/include/psibase/Table.hpp, services/user/Tokens/include/services/user/tokenTables.hpp, services/user/Tokens/src/RTokens.cpp
* Adds the `SplitKey` type to the token query service to allow subindexing on indices with a struct key
* Eliminates redundant token table indices
=> Add `SplitKey` type for subindexing in token query service

rust/burst-transfer/src/main.rs, rust/fracpack/src/fracpack.rs, rust/psibase_macros/src/fracpack_macro.rs, rust/test_fracpack/src/lib.rs, rust/test_fracpack/tests/test.cpp, rust/test_fracpack/tests/test.hpp, rust/test_fracpack/tests/test.rs
Fracpack fix, plus adjust the `burst-transfer` rust tool just to fix our `cargo build`.
=> Rust Fracpack: Omit trailing optionals

CMakeLists.txt, services/user/Nft/include/services/user/Nft.hpp, services/user/Nft/include/services/user/nftTables.hpp, services/user/Nft/src/Nft.cpp, services/user/Nft/test/src/Nft-test.cpp
* Updates the event emission to use the new `events` service.
* Removes old event tracking data from tables
* Updates queries (makes them similar to the new token service queries)
=> Update nft service

CMakeLists.txt
I noticed the token app has a plugin, but it's not automatically deployed. This deploys it to the chain by default.
=> Deploy token plugin by default

services/system/Accounts/include/services/system/Accounts.hpp, services/system/Accounts/src/RAccounts.cpp
Allows the accounts plugin to more easily implement a check for whether a particular account exists, which then enables third-party plugins to check for the existence of accounts.
=> add account exists query

libraries/psibase/CMakeLists.txt, libraries/psibase/tester/src/chain_polyfill.cpp, libraries/psibase/tester/src/tester.cpp, programs/psitest/main.cpp, rust/psibase/src/tester.rs, rust/psibase/src/tester_raw.rs, rust/psibase_macros/src/service_macro.rs
The chain handle is explicitly passed to all the host functions that require it. This requires extra polyfills in the tester.
Also,
- Replace tester's `writeConsole` with `write` to STDOUT.
- Put tester host functions in the `psibase` module.
=> Move tracking of selected chain to wasm

rust/CMakeLists.txt
The extra debug build takes a while and generates ~5GiB of build artifacts. This seems to be the main reason why CICD has started failing.
=> Build rs-tests in release mode to reduce total size

.gitmodules, external/CMakeLists.txt
- fmt is not used. If we do need it, it was standardized in C++20, and is available in both libstdc++ and libc++
- mdbook-mermaid is used in the docs, but not via the submodule
=> Remove unused submodules

programs/psinode/main.cpp
I think at one point it was using milliseconds, and I missed to_string when I changed it to microseconds.
=> Fix writing http-timeout to the config file

libraries/psibase/native/src/ConfigFile.cpp
It caused this:
```
= localhost:
```
because we edit a line by deleting and reinserting it and then the second instance attempts to read the key name (`service`) from a line that has been cleared, which causes it to get a blank key.
=> Fix bug writing config file with duplicated hostname

services/user/Supervisor/ui/src/pluginHost.ts
Supervisor was returning graphql errors as successes, which caused unrelated downstream issues because everything downstream was expecting good results but getting body = "errors": { ...error stuff... }
Now graphql errors are thrown in the JS context
=> Propagate graphql errors as errors instead of success response

services/user/XAdmin/ui/yarn.lock
Not sure this will stop the problem, but it seems to be the only one that gets updated eveyr build, so worth a shot.
=> Updating X-admin's yarn.lock so we don't see it updated every time we build

doc/psidk/src/development/services/rust-service/package.md, rust/cargo-psibase/src/package.rs, rust/psibase/src/block.rs, rust/test_package/query/Cargo.toml, rust/test_package/service/Cargo.toml, rust/test_package/service/src/lib.rs, rust/test_package/ui/index.html
I think that `yarn` can be run via `build.rs`, but I haven't tried it.
=> Add postinstall and data to cargo psibase package

libraries/debug_eos_vm/dwarf.cpp
It makes `catch throw` unusable. This particular case only appears in orphaned debug info.
Note: Most changes are just clang-format. There are two real changes in the translation of `dw_op_wasm_location`.
=> Avoid throwing exceptions when parsing DWARF

CMakeLists.txt
Also, automatically download the correct tarball for arm now that wasi-sdk provides prebuilt arm binaries.
See also: https://github.com/gofractally/image-builders/pull/42
=> Update to wasi-sdk-24.0.

programs/psinode/main.cpp
In some cases a psinode config that specifies a `database-cache-size` would have that property commented out automatically by psinode which did not recognize the key (since it DNE in `PsinodeConfig`). This change should fix that.
=> do not comment out valid config item: database-cache-size

libraries/psio/include/psio/check.hpp, libraries/psio/include/psio/view.hpp
It's currently stubbed to abort and the message from a direct call to abortMessage is better.
It also violates the ODR when mixing translation units compiled with exceptions enabled/disabled.
=> Avoid throwing in WASM builds even when exceptions are "enabled"

CMakeLists.txt, doc/psidk/src/development/services/rust-service/package.md, libraries/psibase/sdk/pack_service.cmake, rust/cargo-psibase/src/package.rs, rust/psibase/src/services/events.rs, rust/test_package/Cargo.toml, services/user/Chainmail/Cargo.lock, services/user/Chainmail/Cargo.toml, services/user/Chainmail/plugin/Cargo.toml, services/user/Chainmail/service/Cargo.toml, services/user/Chainmail/service/src/lib.rs
This PR ensures that the ChainMail app is deployed to the chain by default.
To accomplish this, the [new functionality](https://github.com/gofractally/psibase/pull/840) in `cargo-psibase` that allows for UI and postinstall scripts to be specified is leveraged in chainmail.
Also, this PR introduces a new CMake function `cargo_psibase_package` that allows psibase devs to tell CMake about packages that are built using `cargo-psibase package` rather than using the CMake `psibase_package` function. Therefore cargo-psibase-managed packages can be integrated into the regular build system just like the other packages.
=> Default deploy chainmail

services/user/Branding/ui/src/App.tsx
I mistakenly included a debugging line I meant to revert before the PR. It got missed and committed by mistake. This just reverses that line.
=> Chainmail: patching line of debugging code

.github/workflows/on-tag.yml
The `ubuntu-builder` was changed to v4 upload [here](https://github.com/gofractally/psibase/pull/849/files)
But the `download-artifact` version used in the `on-release.yml` workflow was still on V3 (which is [not supported](https://github.com/actions/download-artifact/blob/main/README.md#breaking-changes)).
=> use v4 download

services/system/HttpServer/src/HttpServer.cpp
Shortcoming with the http server impl was discovered specifically when dealing with SPAs:
For example:
Chainmail is registered as an SPA, so any request that doesn't specify an extension (which would imply a request for a static asset e.g. `style.css`) it assumes is a client route and returns the root document. But that means that API requests like `/messages/sender=alice` are just returning the root document.
This PR reverses the order in which the servers are checked, checking the registered server first. Only check sites iff the registered server returns `None`.
=> Allow SPAs with registered http server to serve rest endpoints

doc/psidk/src/development/services/rust-service/package.md, doc/psidk/src/development/services/rust-service/testing.md
=> improve rust psibase package docs

services/user/Chainmail/service/src/lib.rs, services/user/Chainmail/ui/src/components/mail-display.tsx, services/user/Chainmail/ui/src/lib/utils.ts, services/user/CommonApi/common/packages/common-lib/src/messaging/FunctionCallRequest.ts, services/user/CommonApi/common/packages/common-lib/src/messaging/FunctionCallResponse.ts, services/user/CommonApi/common/packages/common-lib/src/supervisor.ts, services/user/Supervisor/ui/src/appInterace.ts, services/user/Supervisor/ui/src/main.ts, services/user/Supervisor/ui/src/supervisor.ts
This implements a promise queue. Now supervisor can handle multiple requests simultaneously instead of just one.
=> Supervisor: Handle multiple requests simultaneously

services/user/CommonApi/common/packages/common-lib/src/messaging/FunctionCallRequest.ts, services/user/CommonApi/common/packages/common-lib/src/messaging/FunctionCallResponse.ts, services/user/CommonApi/common/packages/common-lib/src/supervisor.ts, services/user/Supervisor/ui/src/supervisor.ts
`window.crypto.randomUUID()` is not available in non-secure contexts (_i.e._, HTTP). While UUIDs are best for this, there's no harm falling back to `Math.random`, as this has little to do with security. This is implemented for the benefit of developers running test chains on HTTP.
=> Supervisor: requestId fallback for non-secure contexts

libraries/psibase/sdk/toolchain.cmake
`psibase-config.cmake` isn't found reliably. CMake takes a shotgun approach to finding xxx-config.cmake, so it *sometimes* works depending on the environment. Explicitly setting `psibase_ROOT` should make it reliable.
=> Fix doc-examples build

CMakeLists.txt
`alice` and `bob` accounts are created by default when booting the dev chain via the `TokenUsers` package. But they are not auth-any, as they previously were.
The auth system is still under heavy development. `getAvailableAccounts` still simply returns `alice` and `bob`, independent of whatever accounts actually exist on the chain.
Applications, such as Chain Mail, are also under development. They currently use those two accounts in auth-any mode.
Removing their default creation by `TokenUsers` (which creates them without auth-any) means that we can create those accounts manually after the chain boots so that Chain Mail can still use them while we continue building everything out.
=> Prevent TokenUsers from automatically deploying on dev chain boot

services/system/AuthSig/src/Spki.cpp
||before|after|
|-|-|-|
|AuthSig.wasm|779255|250029|
|AuthInvite.wasm|902172|375551|
|Invite.wasm|1234002|709177|
=> Simplify SubjectPublicKeyInfo validation to reduce code bloat.

.github/workflows/ubuntu-builder.yml
Updates the builder image for ci/cd. Changes:
* https://github.com/gofractally/image-builders/pull/44
* https://github.com/gofractally/image-builders/pull/45
=> update ci/cd builder image

programs/psinode/CMakeLists.txt, programs/psinode/tests/test_exception_exit.py
`push_transaction` might not return a response before the node shuts down.
=> Fix unreliable test

services/system/AuthSig/include/services/system/AuthSig.hpp, services/system/AuthSig/plugin/src/lib.rs, services/system/AuthSig/plugin/wit/world.wit, services/system/AuthSig/src/RAuthSig.cpp
* Adds the capability to import external keypairs into auth-sig.
* Changes the secondary index for the key table in auth-sig to use the key fingerprint instead of the full public key. This is just to save space
=> Add auth-sig key import

libraries/psibase/CMakeLists.txt, libraries/psibase/common/include/psibase/Rpc.hpp, libraries/psibase/common/src/Rpc.cpp, rust/Cargo.lock, rust/psibase/Cargo.toml, rust/psibase/src/http.rs, services/Cargo.lock, services/user/Branding/Cargo.lock, services/user/Brotli/Cargo.lock, services/user/Chainmail/Cargo.lock, services/user/Chainmail/service/src/event_query_helpers.rs, services/user/Packages/src/RPackages.cpp, services/user/Registry/Cargo.lock, services/user/Sites/src/Sites.cpp
- Add utility functions to HttpRequest to decode the path and query
- Sites (the main service that is likely to need encoded URLs) uses request.path() to decode the path
- Chainmail and Packages use request.query() to parse the query.
Fixes #257
=> Handle percent encoded URLs

libraries/net/include/psibase/blocknet.hpp, libraries/net/test/fuzz.cpp, libraries/net/test/test_bft_consensus.cpp, libraries/net/test/test_consensus.cpp, libraries/net/test/test_signatures.cpp, libraries/net/test/test_util.cpp, libraries/net/test/test_util.hpp, programs/psinode/main.cpp, rust/psibase/src/boot.rs, rust/psibase/src/rpc.rs, services/system/Transact/include/services/system/RTransact.hpp, services/system/Transact/include/services/system/Transact.hpp, services/system/Transact/src/RTransact.cpp, services/system/Transact/src/Transact.cpp
- `push_transaction` can return a packed trace (`application/octet-stream`) instead of JSON to avoid exceeding the service memory limit.
=> Use transact instead of /native/push_transaction

libraries/psibase/tester/src/DefaultTestChain.cpp, services/system/AuthSig/CMakeLists.txt, services/system/AuthSig/include/services/system/AuthSig.hpp, services/system/AuthSig/src/AuthSig.cpp, services/system/AuthSig/test/CMakeLists.txt, services/system/AuthSig/test/src/AuthSig-test.cpp, services/system/CMakeLists.txt, services/system/StagedTx/service/cpp/include/services/system/StagedTx.hpp, services/system/StagedTx/service/src/lib.rs
Adds staged-tx support to auth sig.
The strategy is simply to allow anyone to add a staged tx on behalf of the account, anyone can also accept or reject the transaction, but it doesn't do anything unless the actor is the sender of the staged tx, in which case:
* accept -> execute
* reject -> remove
=> Auth sig support staged tx

services/user/XAdmin/ui/src/components/forms/block-producer.tsx, services/user/XAdmin/ui/src/components/forms/chain-mode-form.tsx, services/user/XAdmin/ui/src/pages/create-page.tsx
I always use this UI to boot my development chains. A couple things that always got me:
1. I click on Development or Production to make my choice. I get confused when nothing happens. Oh yeah, I have to click the next arrow at the bottom! I always forget that. So I make it proceed automatically to the next step when I make my selection.
2. I always press RETURN after I enter the name of my producer. And it triggers default form submission behavior attempting to redirect me to a non-existent submission route. Then I have to start all over. Not a big deal. But this makes it so that the RETURN/ENTER button moves me on to the next step instead.
=> XAdmin boot form UX enhancements

rust/psibase/src/services/transact.rs, services/system/AuthAny/include/services/system/AuthAny.hpp, services/system/AuthAny/src/AuthAny.cpp, services/system/AuthSig/include/services/system/AuthSig.hpp, services/system/AuthSig/src/AuthSig.cpp, services/system/StagedTx/service/Cargo.toml, services/system/StagedTx/service/cpp/include/services/system/StagedTx.hpp, services/system/StagedTx/service/src/lib.rs, services/system/Transact/include/services/system/Transact.hpp
* make staged-tx a sudo service
* simplify auth service interface
* update staged tx service:
* simplify interface
* allow staging a single tx containing actions from multiple senders
* use new auth service interface
=> Rework staged tx

rust/cargo-psibase/src/main.rs
Fixes argument ordering when passing args to `psibase`.
Adds the `--reinstall` option to `cargo-psibase install` for better parity with psibase cli.
=> cargo-psibase fixes/improvements

services/user/CommonApi/common/packages/common-lib/src/supervisor.ts
@Velua discovered a race condition in the supervisor `onLoaded()` function. We patched that. Additionally, instead of forcing apps to call `onLoaded()` prior to making `functionCall()`s to supervisor, we call `this.onLoaded()` inline in the `functionCall()` method itself. This reduces a lot of app boilerplate and simplifies supervisor instantiation and consumption.
=> Fix supervisor onLoaded race condition and reduce burden on apps

services/user/XAdmin/ui/src/components/forms/confirmation-form.tsx
Previously was set to 30 and we're just going over that amount in `.psi` packages. Expanding to `999` for now, can look into pagination later if we want.
This is purely a UI change.
=> change pagination page size on x-admin

services/user/Branding/Cargo.lock, services/user/Branding/Cargo.toml, services/user/Branding/plugin/Cargo.toml, services/user/Branding/service/Cargo.toml, services/user/Branding/src/lib.rs, services/user/Sites/src/Sites.cpp
I noticed the branding app was failing by not being able to download the branding plugin.
I thought it was something to do with the branding package so I matched the syntax in the package config with the conventions established in the package-template. But it still didn't work.
Culprit ended up being the sites service implementation, which the branding plugin was dependent on.
=> Branding plugin not loading

libraries/psio/include/psio/graphql.hpp, libraries/psio/tests/graphql.cpp, services/user/Invite/plugin/src/lib.rs
Adds block string support, escape sequences, unicode escapes, and in general tries to better follow the [graphql spec](https://spec.graphql.org/October2021/#sec-String-Value) for string parsing.
=> Improve cpp graphql support

services/system/Accounts/plugin/accounts/src/interfaces/admin.rs
Needed by x-admin to import the producer account into the browser.
=> Allow foreign account import into accounts app

rust/psibase/src/time.rs, services/user/Registry/plugin/src/queries.rs, services/user/Registry/service/src/lib.rs
Otherwise graphql returns a timepointusec in a form that serde is unable to deserialize into a rich object
=> Align graphql and json timepointusec serialization

rust/cargo-psibase/src/main.rs, rust/cargo-psibase/src/package.rs, services/user/Chainmail/src/lib.rs
This serves two purposes
- It detects errors that could otherwise be missed when the package root isn't actually compiled
- It runs the build scripts for the package and its dependencies
=> Build the root of each package

doc/psidk/src/run-infrastructure/cli/psinode.md, libraries/psibase_http/handle_request.cpp, libraries/psibase_http/http_session_base.hpp, libraries/psibase_http/include/psibase/http.hpp, libraries/psibase_http/tls_http_session.hpp, programs/psinode/config.in, programs/psinode/main.cpp, programs/psinode/tests/psinode.py, rust/Cargo.lock, rust/psibase/Cargo.toml, rust/psibase/src/main.rs, services/Cargo.lock, services/system/StagedTx/Cargo.lock, services/user/Branding/Cargo.lock, services/user/Brotli/Cargo.lock, services/user/Chainmail/Cargo.lock, services/user/Registry/Cargo.lock, services/user/XAdmin/ui/src/configuration/configuration-page.tsx, services/user/XAdmin/ui/src/configuration/interfaces.ts, services/user/XAdmin/ui/src/configuration/utils.ts, services/user/XAdmin/ui/src/hooks/useConfig.ts
localhost is reserved as a top level domain and browsers consider it and its subdomains secure, even over HTTP.
- To allow localhost:8080 to reach boot, all requests redirect to x-admin when the chain is not booted.
- To avoid a disruptive transition, I added the ability to have multiple host names.
TODO:
=> Use localhost instead of sslip

.github/workflows/changelog-template.json, .github/workflows/generate-changelog.yml
Updates changelog generator version, should produce better/more consistent changelogs.
The action finally supports [nested categories](https://github.com/mikepenz/release-changelog-builder-action/pull/1308).
Also adds a contributors section to the changelog
=> better changelog categories

services/system/Accounts/src/Accounts.cpp, services/system/AuthSig/include/services/system/AuthSig.hpp, services/system/AuthSig/src/AuthSig.cpp, services/user/Invite/src/Invite.cpp, services/user/Invite/test/src/Invite-test.cpp
At some point we restricted the creation of new accounts to the invite service, this reverses that decision.
=> Enable new account creation

rust/psibase/src/trace.rs
```
Error: Failed to boot
Caused by:
```
=> Show the error message even if there are no action traces.

libraries/psibase/native/include/psibase/BlockContext.hpp, libraries/psibase/native/src/BlockContext.cpp, libraries/psibase/native/src/NativeFunctions.cpp, services/psibase_tests/event-service.cpp, services/psibase_tests/event-service.hpp, services/psibase_tests/test_event.cpp
This would brick the chain because `putSequential` used a cached member variable which was not rolled back when the transaction aborted. Remove `BlockContext::databaseStatus` and just look it up as needed.
=> Fix failed transactions that emit events

libraries/psibase/common/include/psibase/Actor.hpp, libraries/psio/include/psio/nested.hpp, libraries/psio/include/psio/schema.hpp, libraries/psio/tests/test_fracpack.cpp, libraries/psio/tests/test_fracpack.hpp
A sync call can make 3 (!) copies of the action args. This reduces it to serialize directly into the buffer passed to call.
=> Reduce copies for sync calls

services/user/XAdmin/ui/src/components/EmptyBlock.tsx, services/user/XAdmin/ui/src/components/forms/key-device-form.tsx, services/user/XAdmin/ui/src/components/nav-header.tsx, services/user/XAdmin/ui/src/configuration/interfaces.ts, services/user/XAdmin/ui/src/hooks/useBranding.ts, services/user/XAdmin/ui/src/hooks/useKeyDevices.ts, services/user/XAdmin/ui/src/lib/chainEndpoints.ts, services/user/XAdmin/ui/src/lib/keys.ts, services/user/XAdmin/ui/src/lib/queryKeys.ts, services/user/XAdmin/ui/src/pages/create-page.tsx, services/user/XAdmin/ui/src/pages/keys-page.tsx, services/user/XAdmin/ui/src/routing.tsx, services/user/XAdmin/ui/src/types.ts
- If the server has an HSM configured, display security devices and public keys after boot.
- Display [un]lock status of security devices and allow admin to unlock security devices.
- Display public keys for all unlocked security devices.
- Copy public keys as hex-encoded DER or PEM and download as `.pem`.
- Make network name in nav header dynamic and link to network home page.
- Loading states, error states and success messaging.
=> View and manage security devices and keys in XAdmin UI

services/system/Transact/plugin/src/db.rs, services/system/Transact/plugin/src/lib.rs, services/user/ClientData/plugin/src/lib.rs, services/user/Supervisor/ui/src/callStack.ts
Avoids temporarily storing actions in localstorage, which fails for large actions (like sites:upload) due to restrictions on kv value size.
CC @Velua
=> Use in memory action construction

libraries/psibase/common/include/psibase/Table.hpp, libraries/psibase/common/include/psibase/db.hpp, libraries/psibase/native/include/psibase/db.hpp, libraries/psibase/native/src/BlockContext.cpp, libraries/psibase/native/src/NativeFunctions.cpp, libraries/psibase/native/src/TransactionContext.cpp, libraries/psibase/native/src/useTriedent.cpp, programs/psinode/tests/test_query.py, rust/psibase/src/db.rs, services/psibase_tests/AsyncQueryService.cpp, services/system/HttpServer/src/HttpServer.cpp
It failed when a retry was required, because the database reverted, but the in memory state did not. The PR moves the relevant state into a new `temporary` database.
Note: I tried to avoid native changes, but any solution I could think of created worse problems like misdirected responses.
=> Fix concurrent push transaction

services/system/Transact/include/services/system/RTransact.hpp, services/system/Transact/src/RTransact.cpp
Decreases the memory requirements of transact by pruning `rawData` out of the transaction trace.
=> Reduce r-transact memory consumption

libraries/psibase/common/include/psibase/Actor.hpp, libraries/psibase/common/include/psibase/Memo.hpp, libraries/psibase/common/include/psibase/Rpc.hpp, libraries/psio/include/psio/fracpack.hpp, libraries/psio/include/psio/nested.hpp, libraries/psio/include/psio/reflect.hpp, libraries/psio/include/psio/to_json.hpp, services/system/CMakeLists.txt, services/system/Transact/CMakeLists.txt, services/system/Transact/src/RTransact.cpp
#1050 didn't actually work because it was only applied to the (unused) form that returns a view.
This reduces the total memory usage to approximately 2 times the size of the trace for fracpack or 3 times the size of the trace for json. Since this is exactly the combined size of the input and output, this is optimal. With this change, I can boot with full JSON traces without errors.
=> Minimize copying of the transaction trace when generating a response

rust/psibase/src/depgraph.rs
This will catch the most common way for package resolution to fail. It's possible to get the warning and still install successfully if the packages with incorrekt dependencies aren't needed. However, the warning always means that there's a problem with the package index.
=> Add a warning when a package isn't found

libraries/net/include/psibase/bft.hpp, libraries/net/include/psibase/cft.hpp, libraries/psibase/native/include/psibase/ForkDb.hpp, programs/psinode/CMakeLists.txt, programs/psinode/tests/test_block_signing.py
They were causing two problems
- When the error appeared while handling an incoming block, it would be treated as if it were a failure to execute the block, which could later cause a report of a consensus failure, when the block becomes irreversible.
- When the error appeared for other incoming messages, it would be treated as an invalid message and force the connection to be closed.
Note that this error handling is still needed even if we try to avoid entering producer mode when the key is missing, because a cryptographic device can be physically removed or otherwise become unavailable at any time and outside our control.
=> Handle errors from failure to sign

programs/psinode/tests/name.py, programs/psinode/tests/psinode.py, programs/psinode/tests/services.py, programs/psinode/tests/test_psibase.py
#1080 and #1087 did not include test cases because the python wrappers lacked support for signing.
=> Add tests for signing transactions with `psibase`

services/user/CommonApi/common/packages/plugin-tester/ui/README.md, services/user/CommonApi/common/packages/plugin-tester/ui/index.html, services/user/CommonApi/common/packages/plugin-tester/ui/src/PluginLoader.tsx, services/user/CommonApi/common/packages/plugin-tester/ui/src/components/ExecutionTabs.tsx, services/user/CommonApi/common/packages/plugin-tester/ui/src/components/inputs/StringInput.tsx
This fixes three issues:
1. String inputs couldn't have newline literals, and using "\n" was getting encoded incorrectly (as "\\n") by json stringify. Now the string input is a textarea so we can use actual newlines.
2. Parameter words that needed to be converted to camelCase were, in some cases, resulting in two entries in `paramValues` (one camelCase and one kebab-case). Now only the camelCase variant should be stored.
3. The embed code was serializing the parameters as an object instead of putting the values in an array.
Also added a readme.
=> Plugin tester fixes

rust/psibase/src/serve_http.rs
The explorer plugin allows for simpler construction of graphql queries
=> use a newer & better graphiql UI

rust/psibase/src/main.rs, rust/psibase/src/rpc.rs
- Remove `--suppress-ok`. The Ok message is always delivered through the `ProgressBar`, which will automatically hide it if stderr is not a terminal.
- Send transaction traces and console to stdout. All other messages for commands that push transactions are sent to stderr. This makes piping the JSON traces to another program reasonable.
=> Clean up CLI printing

rust/cargo-psibase/src/package.rs, rust/test_contract/src/lib.rs
Mainly useful to avoid name collisions with third-party crates, e.g. brotli.
=> Allow the account name to differ from the crate name.

.vscode/scripts/build.sh, .vscode/scripts/continue.sh, .vscode/scripts/launch.sh, .vscode/scripts/launch_secure.sh, .vscode/tasks.json.sample
For organization, I use bash scripts instead of scripting inline in the `tasks.json` file. This also allows the script to be called from anywhere (useful for multi-root workspaces)
=> improve default vscode tasks/scripts

rust/psibase/src/graph_ql.rs
Subindex is used incorrectly in multiple places.
The new comment at least gives intellisense a bit more info to help minimize misuse.
=> improve subindex doc comment

programs/psinode/tests/psinode.py, programs/psinode/tests/test_psibase.py, rust/psibase/src/main.rs, rust/psibase/src/package.rs
- If the package is installed, indicate if a more recent version is available.
- If the user requested a specific version, indicate the version that is currently installed.
- Make the parsing of command line arguments more lax, to allow the the argument to be foo-1.0 instead of foo-1.0.0, for example
=> Add install status to psibase info output

libraries/psibase/native/tests/CMakeLists.txt
WatchdogTests can fail due to contention. There are two ways this can happen:
- "CpuClock should be associated with the current thread" checks that the cpu time spent in a spin loop is at least 500 µs. This will fail if the thread is suspended for too long.
- "Watchdog threaded" checks that the overrun of the timer is not exceeded by too much. This will fail if the watchdog thread is not scheduled fast enough. I worked around this previously by repeating the test.
Tell ctest to reserve enough cores so the kernel doesn't need to suspend the threads.
=> Try to fix WatchdogTests

libraries/psibase_http/handle_request.cpp, programs/psinode/tests/test_psibase.py, rust/psibase/src/main.rs, rust/psibase/src/package.rs
This allows psibase to detect the errors for various graphql queries related to packages that have a reasonable interpretation for an unbooted chain. e.g. `psibase info` should only show packages from the repository. This used to work, but got broken when I added the redirect in #994.
=> Only redirect GET requests to x-admin

CMakeLists.txt, libraries/psibase/sdk/pack_service.cmake, libraries/psibase/sdk/toolchain.cmake, wasm/toolchain.cmake
CMake < 3.10 is deprecated. Some new warnings (CMP0174 and CMP0177) show up in 3.31.
=> Fix CMake warnings

rust/psibase_macros/psibase-macros-lib/src/service_tables_macro/tables.rs, services/system/StagedTx/service/src/db.rs, services/user/Chainmail/service/src/tables.rs, services/user/Evaluations/service/src/db.rs, services/user/Registry/service/src/tables.rs
primarily, just needed same use for toKey.
Also took the opportunity to clean up use statements that had formerly been needed in packages.
#1189
=> Cleaning up rust sdk for secondary indices

services/system/Accounts/ui/package.json, services/system/AuthSig/ui/package.json, services/system/Producers/ui/package.json, services/user/Branding/ui/package.json, services/user/Branding/ui/tsconfig.json, services/user/CommonApi/common/packages/common-lib/package.json, services/user/CommonApi/common/packages/plugin-tester/ui/package.json, services/user/CommonApi/common/packages/plugin-tester/ui/tsconfig.json, services/user/Evaluations/ui/package.json, services/user/Evaluations/ui/tsconfig.json, services/user/Explorer/ui/package.json, services/user/Explorer/ui/tsconfig.json, services/user/Homepage/ui/package.json, services/user/Homepage/ui/tsconfig.json, services/user/Identity/ui/package.json, services/user/Identity/ui/tsconfig.json, services/user/Permissions/ui/package.json, services/user/Permissions/ui/tsconfig.json, services/user/Supervisor/ui/package.json, services/user/Workshop/ui/package.json, services/user/Workshop/ui/src/pages/Settings.tsx, services/user/Workshop/ui/tsconfig.app.json, services/user/Workshop/ui/tsconfig.node.json, services/user/XAdmin/ui/package.json, services/user/XAdmin/ui/tsconfig.json
FYI, the major change is `tsc --noEmit --SkipLibCheck` --> `tsc -b --noEmit`. Original config was `tsc -b`. The `--noEmit` saves some time each build. The `-b` turns out to be necessary due to our configuration. And the `skipLibCheck` was only needed for Workshop, and that's been added in tsconfig instead of used as a commandline arg.
`references` have also been removed from all tsconfigs that don't have multiple flavors because that changes the behavior of tsc.
=> Fixing the type checking I inadvertently disabled when I added the no-rebuild script

doc/psidk/src/run-infrastructure/administration.md, libraries/psibase/native/src/log.cpp
The log format once allowed a map of `Channel` to formatter. This was changed in e5566155688c535a56b58cc7a893b71956154f6e to use conditionals in the format string instead. I missed one reference to the old format in the docs.
=> Fix out-dated documentation of log formatter

libraries/net/include/psibase/shortest_path_routing.hpp, programs/psinode/tests/test_crash.py
After a node was restarted, it would sometimes not receive consensus related messages, causing the chain to halt.
Nodes running with this update should be able to connect to existing nodes, however, the fix won't be effective for a connection until both nodes are upgraded.
There are still a number of issues in this PR, which will be addressed in a follow-up PR:
- There are still some structures and messages that need to be updated
- There is a small memory leak. After a node is restarted, the old entries are never removed from the tables of the other nodes.
=> Fix routing p2p messages after a node restarts

rust/psibase_macros/psibase-macros-derive/src/fracpack_macro.rs, rust/psibase_macros/psibase-macros-derive/src/schema_macro.rs, rust/test_fracpack/src/lib.rs, rust/test_fracpack/tests/test.rs
Allows struct fields to be ignored during packing. On unpack, the field will be initialized with `Default::default`
=> Add fracpack(skip) attribute

libraries/psibase/native/include/psibase/BlockContext.hpp, libraries/psibase/native/src/BlockContext.cpp, programs/psinode/tests/test_txqueue.py
We were assuming that `callPreverify` always returns a token for each signature, but that was only true when we found a `preverify` callback. Make the implementation uphold that postcondition consistently.
This caused a non-producing node to fail whenever it received a block with a signed transaction.
=> Fix testnet crash

programs/psinode/tests/psinode.py, programs/psinode/tests/services.py, programs/psinode/tests/test_txqueue.py
with `wait_for=applied`, the speculative transaction might fail while the transaction is being applied in a block, which would cause us to check the counter too early.
=> Fix test failure in test_txqueue

services/system/Transact/plugin/src/helpers.rs
Removes some of the clutter from the browser console by trimming the output for printed transactions
=> declutter console

libraries/triedent/include/triedent/gc_queue.hpp, libraries/triedent/include/triedent/region_allocator.hpp, libraries/triedent/src/gc_queue.cpp, libraries/triedent/src/region_allocator.cpp
The code assumed that the `_sequence` for a session is in bounds, but this was not necessarily true. If the session lock was suspended right after reading `_end`, the state of the queue could change arbitrarily before it writes `_sequence`. `session::lock` accounts for this, but it does create a transient out-of-bounds value for `_sequence` that may be seen by `start_wait`. This would cause us to remove too many items from the queue. Clearing these elements was fine, because they were already `nullptr`.  Decrementing `_size`, though, is a big problem, because it is how we know which items in the circular buffer are free and safe to reuse.
=> Fix database corruption caused by reusing memory that a session is accessing

CMakeLists.txt, libraries/psibase/common/include/psibase/Table.hpp, libraries/psio/include/psio/fracpack.hpp, libraries/psio/include/psio/shared_view_ptr.hpp, libraries/psio/include/psio/view.hpp, services/system/Transact/include/services/system/RTransact.hpp, services/system/Transact/src/RTransact.cpp
- Make views packable
- Allow Table::put for shared_view_ptr and for types that are PackableAs<T>
- Avoid unpacking and repacking the trace
=> Reduce memory usage of RTransact::onTrx

.github/workflows/ubuntu-builder.yml, libraries/net/include/psibase/bft.hpp, libraries/net/include/psibase/blocknet.hpp, programs/psinode/CMakeLists.txt, programs/psinode/main.cpp, programs/psinode/tests/predicates.py, programs/psinode/tests/psinode.py, programs/psinode/tests/test_crash.py, programs/psinode/tests/testutil.py
Also add a timer loop, when sending a view change fails, because the hardware device might have transient failures and we won't be notified when it's ready again.
=> BFT: don't get stuck when there is a view change before we unlock our keys

libraries/net/test/test_bft_consensus.cpp, libraries/net/test/test_util.cpp, libraries/psibase/common/include/psibase/Actor.hpp, libraries/psibase/common/include/psibase/block.hpp, libraries/psibase/common/include/psibase/headerValidation.hpp, libraries/psibase/common/include/psibase/nativeTables.hpp, libraries/psibase/native/include/psibase/ForkDb.hpp, libraries/psibase/native/src/BlockContext.cpp, libraries/psibase/tester/include/psibase/tester.hpp, libraries/psibase/tester/src/tester.cpp, programs/psinode/tests/test_block_signing.py, programs/psinode/tests/testutil.py, programs/psitest/main.cpp, programs/snapshot/LightValidator.hpp, services/psibase_tests/CMakeLists.txt, services/psibase_tests/include/services/test/SetWasmConfig.hpp, services/psibase_tests/include/services/test/VerifyWithCall.hpp, services/psibase_tests/programs/CMakeLists.txt, services/psibase_tests/programs/generate_verify_with_call.cpp, services/psibase_tests/src/SetWasmConfig.cpp, services/psibase_tests/src/VerifyWithCall.cpp, services/system/Producers/src/Producers.cpp, services/system/SetCode/src/SetCode.cpp, services/system/Transact/test/Transact-test.cpp
We were using either the default value or the value from the current head block inconsistently, which could cause a consensus failure.
=> Track WasmConfig used for verify services in the block header

services/system/Accounts/plugin/accounts/src/interfaces/admin.rs, services/system/Accounts/plugin/accounts/wit/impl.wit, services/system/Accounts/ui/src/hooks/useLoginDirect.ts, services/user/CommonApi/src/CommonApi.cpp, services/user/Supervisor/ui/src/hostInterface.ts, services/user/Supervisor/ui/src/plugin/pluginHost.ts
Accounts app was setting query-token. That's now incorporated into the Accounts plugin's login_direct() function for better encapsulation.
This PR is a follow on to #1291. Once that's merged, the commit history on this PR will be *very* short
=> Set cookie from plugin

package-templates/basic-01/{{project-name | upper_camel_case}}/Cargo.toml.liquid, package-templates/basic-01/{{project-name | upper_camel_case}}/plugin/Cargo.toml.liquid, package-templates/basic-01/{{project-name | upper_camel_case}}/plugin/src/lib.rs, package-templates/basic-01/{{project-name | upper_camel_case}}/plugin/wit/impl.wit, package-templates/basic-01/{{project-name | upper_camel_case}}/plugin/wit/world.wit
Adds example usage of the `permissions` plugin to manage prompting the user to authorize third-party usage of a plugin on the user's behalf
=> integrate permissions plugin with package-template

packages/system/AuthSig/plugin/src/lib.rs
This fixes x-admin key import for the producer account on secure boot.
=> add missing authsig permission

packages/user/Evaluations/Cargo.lock, packages/user/Evaluations/query-service/Cargo.toml, packages/user/Evaluations/service/Cargo.toml, packages/user/Fractals/Cargo.lock
- ecies indirectly sets features of digest and possibly others
- average sets "libm" feature of num-traits
=> Workaround to avoid always rebuilding evaluations

packages/user/Supervisor/ui/src/localStorageManager.tsx, packages/user/Supervisor/ui/src/main.ts, packages/user/Supervisor/ui/src/mainPage.tsx
Now at `supervisor.tld` there's a more helpful message than "supervisor here", namely it now says:
"This app (supervisor) is intended to be embedded into an app and interacted with via window.postMessage()"
More importantly, there's also now a button to spawn a modal that helps manage localstorage. You can quickly delete all key/value pairs in localstorage that were from old chains.
=> Add localstorage manager to supervisor

packages/user/Permissions/plugin/src/db.rs, packages/user/Permissions/plugin/src/errors.rs, packages/user/Permissions/plugin/src/lib.rs, packages/user/Permissions/plugin/wit/world.wit
The user should only be presented for requests to authorize apps with which they are familiar. They are implicitly familiar with the app they are using (the "active app"), so that app is allowed to call plugin functions that themselves call `permissions:authorize`, but besides that, the active app has to explicitly whitelist other apps that they allow to request permissions from the user while in the context of their app.
For example:
```mermaid
sequenceDiagram
actor A as Alice
participant 1 as App 1
participant 2 as App 2
participant p as Permissions plugin
A->>1: Use the app
1->>2: Calls a function
2->>p: Does Alice trust App 1?
note over p: This request is valid.<br>Alice knows App 1 and can<br>judge trust level
```
```mermaid
sequenceDiagram
actor A as Alice
participant 1 as App 1 …
```
=> Block deeply-nested permissions requests (by default)

libraries/net/include/psibase/auto_timeout.hpp, libraries/net/include/psibase/cft.hpp, libraries/net/include/psibase/direct_routing.hpp, libraries/net/include/psibase/mock_routing.hpp, libraries/net/include/psibase/shortest_path_routing.hpp, libraries/net/test/CMakeLists.txt
The network can be very unstable if the timeout is too low, but it's slow to recover when it's too high. Try to figure out a good value dynamically.
=> Automatically adjust CFT timeout

packages/system/Transact/include/services/system/Transact.hpp, packages/system/Transact/plugin/src/lib.rs, packages/system/Transact/src/RTransact.cpp, packages/system/Transact/src/Transact.cpp, rust/psibase/src/services/transact.rs
* Uses u32 for `setSnapTime` which ensures that it can be returned from queries as a json number instead of getting stringified.
* Adds a query for snapshot info
* Fixes transact plugin, which wasn't easily able to call tx on itself previously
=> Transact snapshot improvements

libraries/psibase/common/include/psibase/Table.hpp, libraries/psibase/common/include/psibase/db.hpp, libraries/psibase/common/include/psibase/nativeTables.hpp, libraries/psibase/common/include/psibase/schema.hpp, libraries/psibase/native/include/psibase/ForkDb.hpp, libraries/psibase/native/include/psibase/db.hpp, libraries/psibase/native/src/BlockContext.cpp, libraries/psibase/native/src/NativeFunctions.cpp, libraries/psibase/native/src/Socket.cpp, libraries/psibase/native/src/useTriedent.cpp, packages/local/XHttp/include/services/local/XHttp.hpp, packages/local/XHttp/src/XHttp.cpp, packages/psibase_tests/src/AsyncQueryService.cpp, packages/system/HttpServer/include/services/system/HttpServer.hpp, packages/system/HttpServer/src/HttpServer.cpp, packages/system/Transact/include/services/system/RTransact.hpp, packages/system/Transact/src/RTransact.cpp, programs/psinode/main.cpp, programs/psitest/main.cpp
These are used to store data that is linked to the psinode process.
- Sockets are a per-process resource, and are always closed when psinode exits. Keeping them open in wasm but transforming the response into a no-op is a bit convoluted.
- The environment can change when psinode starts. It should not be preserved.
=> Add session databases

packages/system/AuthSig/plugin/src/lib.rs
`accounts` should be in the `auth-sig` whitelist for `import`. Otherwise, `auth-sig` will ask the user for permission on account import, and on a new device where the user isn't logged in, there is no user to authorize the `permissions` prompt and account import is therefore impossible.
=> fix account import permissions error

packages/user/CommonApi/common/packages/plugin-tester/ui/src/components/inputs/TypeBasedInput.tsx
type aliases on numeric types (which were recently introduced to the tokens plugin) break the plugin tester dynamic GUI generator. This is a fix
=> fix plugin tester

CMakeLists.txt
1. Evaluations package was missing from proddefault
2. ~~xadmin_js dependencies should have been using `${XAdmin_js_DEP}` instead of `XAdmin_js` (causing issues with detecting changes in xadmin)~~
3. authsig dep re-added to producers package. - Until a better solution is found, this is necessary to ensure verify-sig is published before the setproducers call (which uses verify-sig as the producer claim)
=> Misc cmakelists fixes
